"""add review

Revision ID: 668bb3d49745
Revises: fed51f30c6e5
Create Date: 2024-06-27 22:45:00.570253

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '668bb3d49745'
down_revision = 'fed51f30c6e5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('comment', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reviews')
    # ### end Alembic commands ###
